### PR TITLE
Fix bug that did not allow local Filesystem based repo

### PR DESCRIPTION
**Pull request by janhoy**
The code assumed HttpUrlConnection and fails in classCastException.
Also added some toSting.
There should be some more JUnit tests here :-)

### CODE REVIEW

**Comment by decebals** [comment]
To be honest, it's for the first time when I see that someone uses pf4j-update with a local repository.
Is it not enough to add or update the plugins (zip files) in `pluginsDir` folder (the default value is `plugins`)?
Do you have a real use case for a such feature?
If we need to support a such scenario my feeling is that `FileDownloader` is not the perfect place for modification and we should perform a check somewhere in front of this class.

**Comment by janhoy** [comment]
I'm using it in some tests, and then it is convenient to simulate a repo in the file system.

The project I'm trying to integrate with is Apache Solr. And I can imagine users who use the product behind firewalls without access to the internet, where first downloading one or more online plugin repos to a shared file system and then pointing Solr to those might make sense.

Some users also have multiple Solr clusters, and having a central shared file system repo that each cluster could check for updates against sounds useful.

Of course such users could also serve the same files from a local Nginx or similar, but that is one more thing to manage...

**Comment by decebals** [comment]
I took a look in actual code.

I see that I have two repositories json in the root of project:
- [repositories,json](https://github.com/decebals/pf4j-update/blob/master/repositories.json)
- [repositories-folder.json](https://github.com/decebals/pf4j-update/blob/master/repositories-folder.json)

So my feeling is that the actual code works with the folder repositories.

If it doesn't work to accommodate your request in the actual code  with minimal impact I see these steps:
- create a new `getPluginFile(String url)` in `UpdateManager`
- use the above method in `installPlugin` and `updatePlugin` (instead of FileDownloader)

The implementation of `getPluginFile(String url)` looks something like (the pseudocode)
```
if (url is a file) {
   return the file
} else {
   download the file via FileDownloader
   return the file
}
```

**Comment by janhoy** [comment]
Makes sense I guess, that if the URL is indeed a local file, then no need to first copy it, if you are anyway going to unzip and then remove the original zip?

**Comment by decebals** [comment]
I don't understand your last comment.
First, it's not clear for me if the actual code works for your scenario with local repo (I think that if you declare the url of repo like in repository-folder.json, it should be OK).

> Makes sense I guess, that if the URL is indeed a local file, then no need to first copy it, if you are anyway going to unzip and then remove the original zip?

It's the responsibility of the `PluginManager` to install the plugin in application (the `DefaultPluginLoader` unzip plugins archives from pluginsDir), the `UpdateManager` only fetch plugins files to pluginsDir.  We don't remove the zip archive (from PluginManager or UpdateManager).

**Comment by janhoy** [comment]
No problems when using HTTP repo. 

The test coverage is a bit lacking. Perhaps I get to write some unit tests later.

**Pull request closed without merging**
